import os
print(os.path.exists("./tests/lines_3d.png"))
print(os.path.exists("./tests/bbb/"))
print(os.path.exists("./tests/tests"))
print(os.path.exists("./tests/tests/"))
#os.mkdir("./tests/bbb/")
#os.mkdir("./tests/aaa")
print("./".endswith("/"))
filepath, filename = os.path.split("test_path.py")
print(filepath)
print(filename)
filepath, filename = os.path.split("./tests/test_path.py")
print(filepath)
print(filename)